version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/gejustin/ruby-nx-monorepo"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "ruby"