# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gem-b.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rubocop", "~> 1.36"

gem 'gem-a', path: '../gem-a'
